### ISSUE TITLE
splatoon 1 infinitely loads

### ISSUE THREAD

**Issue by skweed767** [PretendoNetwork/splatoon#1]
title says it all
https://www.youtube.com/watch?v=qg_vYC1JeWQ it just kept going

**Comment by Anxiemon** [comment]
Check your internet. Or just reboot your Wii U.

**Comment by that1polish** [comment]
Yea idk if internet would cause this is this a real Wii U or emulator

**Comment by PokeyManatee4** [comment]
I'll need a scenario to test this

**Comment by Anxiemon** [comment]
Is this issue still persisting?
if not, please close this lol

**Comment by ashquarky** [comment]
Re-file this if it's still happening, using our issue templates
