### ISSUE TITLE
[Enhancement]: Port to matchmaking rewrite

### ISSUE THREAD

**Issue by ashquarky** [PretendoNetwork/splatoon#9]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

Dani has been hard at work at a [complete rewrite of the matchmaking code in nex-protocols-common-go](https://github.com/PretendoNetwork/nex-protocols-common-go/pull/35). It uses a Postgres database for room state, eliminating race conditions and state inconsistencies (we hope) - it also correctly implements more NEX notification types, including those needed for Splatfest matchmaking. We also expect to see moderation improvements from examining the database.

It'd be nice to bring these improvements to Splatoon.

### Any other details to share? (OPTIONAL)

Some experimental work has happened in Minecraft: https://github.com/PretendoNetwork/minecraft-wiiu/tree/work/mm-rewrite

External contributors please note that the matchmaking rewrite is **not final** and **may not be merged** in its current state. Consider this experimental work to see if the improvements stick, which may be dropped from no fault of your own. Don't expect a merge into the main Splatoon branch until the matchmaking-rewrite also merges, but we'd love to experiment with such a build in the meantime.

**Comment by ssdrive-flaktra** [comment]
I'm working on a build of the splatoon server with this rewrite, will update here and make a pull request when it's ready.
